name: Neptune-AI WorkFlow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Install Python Dependencies
        run: |
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          flake8 . --max-line-length=85 --statistics
        continue-on-error: false
      
      - name: black formatter
        uses: rickstaa/action-black@v1
        with:
          black_args: ". --check"
      
      - name: Test with pytest
        run: |
          pytest ../neptunelearn/tests --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
      
      
