name: Neptune-AI WorkFlow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Install Python Dependencies
        run: |
            if [ -f requirements.txt ]; then pip install -r requirements.txt;

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --max-line-length=85 --statistics
        continue-on-error: false
      
      - name: Run tests and coverage
        run: pytest tests --cov=neptunelearn/linear_models --cov-report=json
          
      
      
