name: Neptune-AI WorkFlow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: List with flake8
        run: |
          pip install flake8
          flake8 .
        continue-on-error: false
